// Postgres-backed Store (ADR-0004: Postgres is truth in prod). Mirrors
// store_sqlite.go — same tables, same JSON-text spec columns, same
// transactional-outbox semantics — with only true dialect adaptations:
//
//   - Placeholders $1, $2, … instead of ?.
//   - INTEGER -> BIGINT (generations and unix-second columns are uint64,
//     bound as int64 with the same clampI64 saturation store_sqlite.go
//     uses). REAL -> DOUBLE PRECISION (quantity is float64).
//   - audit_events.seq INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT
//     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY; INSERT … RETURNING seq
//     replaces db.LastInsertId (database/sql's sqlite path), which pgx has
//     no equivalent of.
//   - Boolean-as-int columns (local_users.disabled, api_tokens.revoked)
//     become real BOOLEAN columns bound as Go bool — no int/bool
//     conversion helpers needed, unlike SqliteStore's disabled/revoked
//     int64 shuffling.
//   - Scalar MAX(a, b) -> GREATEST(a, b) in RecordObservation (Postgres's
//     MAX is aggregate-only).
//   - SqliteStore's BEGIN IMMEDIATE (serialize writers up front via the
//     _txlock=immediate DSN option) becomes a real transaction plus
//     pg_advisory_xact_lock(hashtext($1)) on the read-modify-write paths
//     (UpsertDesired, UpsertPool, BeginIntent, RecordAudit), so two
//     concurrent upserts/appends on the same key serialize across
//     connections AND processes — the correctness property multi-replica
//     Postgres deployments need that SqliteStore's single-process auditMu
//     mutex cannot provide. Plain SELECT … FOR UPDATE cannot serialize the
//     insert-of-a-new-key race; the advisory lock covers both.
//   - No ALTER-TABLE-if-missing / chain-hash-backfill step: same ADR-0004
//     ruling store_sqlite_schema.go documents (no production legacy
//     Bifrost chains exist), so audit_events.chain_hash is TEXT NOT NULL
//     with no default and this file has no migration pass at all — the
//     retired Rust reference's #59 backfill (store_postgres.rs:230-264)
//     has nothing to port here for the same reason.
//
// ADR-0001 #4 deviation (recorded here per the task-4 dispatch): the ADR
// names pgx v5 + sqlc for Postgres. This file uses plain pgx v5
// (pgxpool.Pool, hand-written SQL strings) instead, matching
// store_sqlite.go's plain database/sql style rather than introducing a
// second query-authoring convention (sqlc-generated Queries) alongside it
// in the same Wave. Consistency between the two SQL-backed siblings — same
// method shapes, same helper functions (scanCluster, clampI64, jsonErr,
// …), same review surface — outweighs sqlc's compile-time query checking
// for this wave. A follow-up can introduce sqlc across both backends at
// once if that checking is wanted later; see the task-4 report for the
// full rationale.
//
// Ported from mobula-controller/src/store_postgres.rs (retired Rust
// reference; cited here only for the file:line references that make
// porting traceable — never in user-facing strings).
package controller

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/brandonrc/bifrost/internal/core"
)

// PostgresStore is a pgx-backed Store: the production backend (ADR-0004).
type PostgresStore struct {
	pool *pgxpool.Pool
}

var _ Store = (*PostgresStore)(nil)

// postgresSchemaStatements are the DDL statements applied by
// NewPostgresStore/NewPostgresStoreFromPool, one per Exec call (Postgres,
// unlike SQLite's db.ExecContext(ctx, multiStatementString), does not run
// multiple commands through the extended/prepared protocol pgx's pool
// uses by default — splitting into individual statements sidesteps that
// entirely instead of depending on a specific pgx query-exec-mode choice).
// Same tables as sqliteSchema; see the package doc comment above for the
// dialect adaptations.
var postgresSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS clusters (
	    id                  TEXT PRIMARY KEY,
	    spec_json           TEXT NOT NULL,
	    generation          BIGINT NOT NULL,
	    desired             TEXT NOT NULL,
	    observed_state      TEXT,
	    observed_generation BIGINT NOT NULL DEFAULT 0,
	    condition           TEXT,
	    failure_count       BIGINT NOT NULL DEFAULT 0,
	    next_attempt_at     BIGINT NOT NULL DEFAULT 0,
	    created_at          BIGINT NOT NULL DEFAULT 0,
	    terminated_at       BIGINT
	)`,
	`CREATE TABLE IF NOT EXISTS intents (
	    intent_key         TEXT PRIMARY KEY,
	    params_fingerprint TEXT NOT NULL DEFAULT '',
	    status             TEXT NOT NULL DEFAULT 'applied',
	    response_json      TEXT,
	    created_at         BIGINT NOT NULL DEFAULT 0,
	    completed_at       BIGINT
	)`,
	// Singleton control flags: quarantine (#41) and the governance policy row.
	`CREATE TABLE IF NOT EXISTS control (
	    key   TEXT PRIMARY KEY,
	    value TEXT NOT NULL
	)`,
	// Persistent job history. Deliberately no foreign key to clusters:
	// records outlive the clusters that ran them.
	`CREATE TABLE IF NOT EXISTS jobs (
	    id            TEXT PRIMARY KEY,
	    cluster       TEXT NOT NULL,
	    submitter     TEXT NOT NULL,
	    status        TEXT NOT NULL,
	    duration_secs BIGINT,
	    submitted_at  BIGINT NOT NULL
	)`,
	// Capacity pools (ADR-0010): the store is truth; Kueue objects are
	// actuation. observed_json holds the pool reconcile loop's last
	// ClusterQueue status observation (opaque JSON).
	`CREATE TABLE IF NOT EXISTS pools (
	    name          TEXT PRIMARY KEY,
	    spec_json     TEXT NOT NULL,
	    generation    BIGINT NOT NULL,
	    observed_json TEXT,
	    observed_at   BIGINT,
	    created_at    BIGINT NOT NULL DEFAULT 0
	)`,
	// Per-project allocations within a pool, keyed by (pool, project).
	`CREATE TABLE IF NOT EXISTS allocations (
	    pool      TEXT NOT NULL,
	    project   TEXT NOT NULL,
	    spec_json TEXT NOT NULL,
	    PRIMARY KEY (pool, project)
	)`,
	// Usage metering timeseries: append-only, no primary key. project = ''
	// is the pool-level aggregate row; pool = '' means the project has no
	// allocation. source is 'kueue_ledger' or 'observed_spec'.
	`CREATE TABLE IF NOT EXISTS usage_samples (
	    ts       BIGINT NOT NULL,
	    project  TEXT NOT NULL,
	    pool     TEXT NOT NULL,
	    resource TEXT NOT NULL,
	    quantity DOUBLE PRECISION NOT NULL,
	    source   TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS usage_samples_project_ts ON usage_samples (project, ts)`,
	// Persisted audit trail (api-v1.md §5.9): append-only. seq is the
	// pagination cursor (rows are read newest-first). chain_hash is the
	// tamper-evidence chain (see AuditChainHash in store.go); genesis
	// chains from AuditGenesisHash. NOT NULL with no default, matching
	// sqliteSchema's ADR-0004 deviation from the Rust reference's
	// `DEFAULT ''` (that default existed there only for the pre-chain
	// backfill pass this file has no equivalent of).
	`CREATE TABLE IF NOT EXISTS audit_events (
	    seq           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    ts            BIGINT NOT NULL,
	    subject       TEXT,
	    decision      TEXT NOT NULL,
	    reason        TEXT,
	    action        TEXT,
	    cluster       TEXT,
	    method        TEXT,
	    path          TEXT,
	    status        BIGINT,
	    latency_ms    BIGINT,
	    required_json TEXT,
	    granted_roles TEXT NOT NULL DEFAULT '[]',
	    chain_hash    TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS audit_events_ts ON audit_events (ts)`,
	// Local auth (ADR-0011): users and opaque API tokens. Bifrost stores
	// credentials, never signs them — both secret columns hold bcrypt
	// hashes. disabled/revoked are real BOOLEAN columns here (SqliteStore
	// stores them as INTEGER 0/1 — see pgScanLocalUser/pgScanApiToken).
	`CREATE TABLE IF NOT EXISTS local_users (
	    username      TEXT PRIMARY KEY,
	    email         TEXT,
	    password_hash TEXT NOT NULL,
	    role          TEXT NOT NULL,
	    disabled      BOOLEAN NOT NULL DEFAULT FALSE,
	    created_at    BIGINT NOT NULL DEFAULT 0,
	    failed_logins BIGINT NOT NULL DEFAULT 0,
	    locked_until  BIGINT
	)`,
	// Opaque API tokens (mob_<prefix>_<32 hex>). The 8-char prefix is the
	// lookup key; the plaintext token is never stored.
	`CREATE TABLE IF NOT EXISTS api_tokens (
	    prefix       TEXT PRIMARY KEY,
	    token_hash   TEXT NOT NULL,
	    username     TEXT NOT NULL,
	    label        TEXT NOT NULL,
	    created_at   BIGINT NOT NULL DEFAULT 0,
	    expires_at   BIGINT NOT NULL,
	    revoked      BOOLEAN NOT NULL DEFAULT FALSE,
	    last_used_at BIGINT
	)`,
	`CREATE INDEX IF NOT EXISTS api_tokens_username ON api_tokens (username)`,
	// Scoped role assignments: scope is '*' (global) or 'project:<name>';
	// role is the auth package's Role wire name. Keyed by the full triple
	// so re-upsert replaces; the (principal) prefix serves the per-request
	// authz lookup.
	`CREATE TABLE IF NOT EXISTS role_assignments (
	    principal  TEXT NOT NULL,
	    role       TEXT NOT NULL,
	    scope      TEXT NOT NULL,
	    created_at BIGINT NOT NULL DEFAULT 0,
	    PRIMARY KEY (principal, role, scope)
	)`,
}

// applyPostgresSchema runs postgresSchemaStatements one at a time —
// idempotent (every CREATE is IF NOT EXISTS), so NewPostgresStore /
// NewPostgresStoreFromPool can reapply it on every boot.
func applyPostgresSchema(ctx context.Context, pool *pgxpool.Pool) error {
	for _, stmt := range postgresSchemaStatements {
		if _, err := pool.Exec(ctx, stmt); err != nil {
			return storeErrorf("apply postgres schema: %v", err)
		}
	}
	return nil
}

// NewPostgresStore connects to url (a postgres:// connection string) and
// applies the schema.
func NewPostgresStore(ctx context.Context, url string) (*PostgresStore, error) {
	pool, err := pgxpool.New(ctx, url)
	if err != nil {
		return nil, storeErrorf("connect postgres: %v", err)
	}
	store, err := NewPostgresStoreFromPool(ctx, pool)
	if err != nil {
		pool.Close()
		return nil, err
	}
	return store, nil
}

// NewPostgresStoreFromPool wraps an existing pool, applying the schema to
// its search_path — e.g. tests that pin a per-test schema via
// pgxpool.Config.AfterConnect for isolation (store_postgres.rs:224-227's
// from_pool equivalent).
func NewPostgresStoreFromPool(ctx context.Context, pool *pgxpool.Pool) (*PostgresStore, error) {
	if err := applyPostgresSchema(ctx, pool); err != nil {
		return nil, err
	}
	return &PostgresStore{pool: pool}, nil
}

// Close releases the underlying connection pool. Deliberately not part of
// the Store interface, same rationale as SqliteStore.Close.
func (s *PostgresStore) Close() error {
	s.pool.Close()
	return nil
}

// isPgUniqueViolation reports whether err is a Postgres unique-constraint
// violation (SQLSTATE 23505) — the pgx/pgconn analog of SqliteStore's
// isUniqueViolation string match.
func isPgUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}

// --- Clusters ---

// UpsertDesired mirrors store_postgres.rs:401-466. pg_advisory_xact_lock
// takes a session-scoped, transaction-released lock keyed by the cluster
// id, so two concurrent upserts of the SAME cluster serialize: the second
// waits for the first to commit, then reads the already-bumped
// generation, instead of both reading generation N and collapsing two
// spec changes into one bump (#42's Postgres side — the ledgered
// postgres_concurrent_distinct_upserts_do_not_collapse_generation test in
// store_postgres_test.go exercises exactly this).
func (s *PostgresStore) UpsertDesired(ctx context.Context, id core.ClusterId, spec core.ClusterSpec) (uint64, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return 0, storeErrorf("begin transaction: %v", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if _, err := tx.Exec(ctx, "SELECT pg_advisory_xact_lock(hashtext($1))", string(id)); err != nil {
		return 0, storeErrorf("advisory lock: %v", err)
	}

	generation, err := func() (uint64, error) {
		var curJSON string
		var curGen int64
		err := tx.QueryRow(ctx, "SELECT spec_json, generation FROM clusters WHERE id = $1", string(id)).
			Scan(&curJSON, &curGen)
		switch {
		case err == nil:
			var cur core.ClusterSpec
			if uerr := json.Unmarshal([]byte(curJSON), &cur); uerr != nil {
				return 0, jsonErr(uerr)
			}
			if specChanged(&cur, &spec) {
				return uint64(curGen) + 1, nil
			}
			return uint64(curGen), nil
		case errors.Is(err, pgx.ErrNoRows):
			return 1, nil
		default:
			return 0, storeErrorf("read cluster: %v", err)
		}
	}()
	if err != nil {
		return 0, err
	}

	specJSON, err := json.Marshal(spec)
	if err != nil {
		return 0, jsonErr(err)
	}
	// Keep desired/observed/condition/backoff/created_at on update (not in
	// the DO UPDATE SET list); default desired='running', observed_generation=0
	// on insert.
	_, err = tx.Exec(ctx, `
		INSERT INTO clusters (id, spec_json, generation, desired, observed_generation, created_at)
		VALUES ($1, $2, $3, 'running', 0, $4)
		ON CONFLICT (id) DO UPDATE SET
			spec_json = excluded.spec_json,
			generation = excluded.generation
	`, string(id), string(specJSON), int64(generation), int64(NowUnix()))
	if err != nil {
		return 0, storeErrorf("upsert cluster: %v", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return 0, storeErrorf("commit: %v", err)
	}
	return generation, nil
}

func (s *PostgresStore) Get(ctx context.Context, id core.ClusterId) (*StoredCluster, error) {
	row := s.pool.QueryRow(ctx, "SELECT "+clusterColumns+" FROM clusters WHERE id = $1", string(id))
	c, err := scanCluster(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &c, nil
}

func (s *PostgresStore) List(ctx context.Context) ([]StoredCluster, error) {
	rows, err := s.pool.Query(ctx, "SELECT "+clusterColumns+" FROM clusters")
	if err != nil {
		return nil, storeErrorf("list clusters: %v", err)
	}
	defer rows.Close()

	out := make([]StoredCluster, 0)
	for rows.Next() {
		c, err := scanCluster(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	if err := rows.Err(); err != nil {
		return nil, storeErrorf("list clusters: %v", err)
	}
	return out, nil
}

func (s *PostgresStore) SetDesired(ctx context.Context, id core.ClusterId, desired DesiredState) error {
	if !desired.isValid() {
		return errBadDesiredState(string(desired))
	}
	isTerminated := desired == DesiredTerminated
	tag, err := s.pool.Exec(ctx,
		`UPDATE clusters SET desired = $1,
		 terminated_at = CASE WHEN $2 THEN COALESCE(terminated_at, $3) ELSE NULL END
		 WHERE id = $4`,
		desired.AsStr(), isTerminated, int64(NowUnix()), string(id))
	if err != nil {
		return storeErrorf("set desired: %v", err)
	}
	if tag.RowsAffected() == 0 {
		return errNoSuchCluster(string(id))
	}
	return nil
}

func (s *PostgresStore) RemoveCluster(ctx context.Context, id core.ClusterId) (bool, error) {
	tag, err := s.pool.Exec(ctx, "DELETE FROM clusters WHERE id = $1", string(id))
	if err != nil {
		return false, storeErrorf("remove cluster: %v", err)
	}
	return tag.RowsAffected() > 0, nil
}

func (s *PostgresStore) RecordObservation(ctx context.Context, id core.ClusterId, observed *core.ClusterState, observedGeneration uint64) error {
	var observedJSON *string
	if observed != nil {
		b, err := json.Marshal(*observed)
		if err != nil {
			return jsonErr(err)
		}
		str := string(b)
		observedJSON = &str
	}
	// GREATEST keeps observed_generation monotonic (#41 stale-generation
	// fence): a restore reporting an older generation can't roll it back.
	// Postgres's MAX() is aggregate-only, unlike SQLite's scalar MAX.
	_, err := s.pool.Exec(ctx,
		"UPDATE clusters SET observed_state = $1, observed_generation = GREATEST(observed_generation, $2) WHERE id = $3",
		observedJSON, int64(observedGeneration), string(id))
	if err != nil {
		return storeErrorf("record observation: %v", err)
	}
	return nil
}

func (s *PostgresStore) SetCondition(ctx context.Context, id core.ClusterId, condition *core.DriftCondition) error {
	var conditionJSON *string
	if condition != nil {
		b, err := json.Marshal(*condition)
		if err != nil {
			return jsonErr(err)
		}
		str := string(b)
		conditionJSON = &str
	}
	_, err := s.pool.Exec(ctx, "UPDATE clusters SET condition = $1 WHERE id = $2", conditionJSON, string(id))
	if err != nil {
		return storeErrorf("set condition: %v", err)
	}
	return nil
}

func (s *PostgresStore) IsQuarantined(ctx context.Context) (bool, error) {
	var v string
	err := s.pool.QueryRow(ctx, "SELECT value FROM control WHERE key = 'quarantine'").Scan(&v)
	switch {
	case err == nil:
		return v == "true", nil
	case errors.Is(err, pgx.ErrNoRows):
		return false, nil
	default:
		return false, storeErrorf("read quarantine: %v", err)
	}
}

func (s *PostgresStore) SetQuarantine(ctx context.Context, quarantined bool) error {
	val := "false"
	if quarantined {
		val = "true"
	}
	_, err := s.pool.Exec(ctx,
		"INSERT INTO control (key, value) VALUES ('quarantine', $1) ON CONFLICT (key) DO UPDATE SET value = excluded.value",
		val)
	if err != nil {
		return storeErrorf("set quarantine: %v", err)
	}
	return nil
}

func (s *PostgresStore) RecordAttempt(ctx context.Context, id core.ClusterId, failureCount uint32, nextAttemptAt uint64) error {
	_, err := s.pool.Exec(ctx,
		"UPDATE clusters SET failure_count = $1, next_attempt_at = $2 WHERE id = $3",
		int64(failureCount), int64(nextAttemptAt), string(id))
	if err != nil {
		return storeErrorf("record attempt: %v", err)
	}
	return nil
}

// --- Transactional outbox ---

// BeginIntent mirrors store_postgres.rs:627-678: opened under a
// transaction + per-key advisory lock so two reconcilers can't both treat
// the same key as fresh.
func (s *PostgresStore) BeginIntent(ctx context.Context, key, fingerprint string) (IntentOutcome, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return IntentOutcome{}, storeErrorf("begin transaction: %v", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if _, err := tx.Exec(ctx, "SELECT pg_advisory_xact_lock(hashtext($1))", key); err != nil {
		return IntentOutcome{}, storeErrorf("advisory lock: %v", err)
	}

	var existingFP string
	err = tx.QueryRow(ctx, "SELECT params_fingerprint FROM intents WHERE intent_key = $1", key).Scan(&existingFP)
	var outcome IntentOutcome
	switch {
	case err == nil:
		if existingFP != fingerprint {
			outcome = IntentOutcome{Kind: IntentOutcomeParamMismatch}
		} else {
			outcome = IntentOutcome{Kind: IntentOutcomeProceed, Replay: true}
		}
	case errors.Is(err, pgx.ErrNoRows):
		if _, err := tx.Exec(ctx,
			"INSERT INTO intents (intent_key, params_fingerprint, status, created_at) VALUES ($1, $2, 'pending', $3)",
			key, fingerprint, int64(NowUnix())); err != nil {
			return IntentOutcome{}, storeErrorf("insert intent: %v", err)
		}
		outcome = IntentOutcome{Kind: IntentOutcomeProceed, Replay: false}
	default:
		return IntentOutcome{}, storeErrorf("read intent: %v", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return IntentOutcome{}, storeErrorf("commit: %v", err)
	}
	return outcome, nil
}

func (s *PostgresStore) CompleteIntent(ctx context.Context, key, responseJSON string) error {
	_, err := s.pool.Exec(ctx,
		"UPDATE intents SET status = 'applied', response_json = $1, completed_at = $2 WHERE intent_key = $3",
		responseJSON, int64(NowUnix()), key)
	if err != nil {
		return storeErrorf("complete intent: %v", err)
	}
	return nil
}

func (s *PostgresStore) GetIntent(ctx context.Context, key string) (*IntentRecord, error) {
	var (
		intentKey    string
		fingerprint  string
		statusStr    string
		responseJSON *string
		createdAt    int64
		completedAt  *int64
	)
	err := s.pool.QueryRow(ctx,
		"SELECT intent_key, params_fingerprint, status, response_json, created_at, completed_at FROM intents WHERE intent_key = $1",
		key).Scan(&intentKey, &fingerprint, &statusStr, &responseJSON, &createdAt, &completedAt)
	switch {
	case err == nil:
		return &IntentRecord{
			Key:               intentKey,
			ParamsFingerprint: fingerprint,
			Status:            parseIntentStatus(statusStr),
			ResponseJSON:      responseJSON,
			CreatedAt:         uint64(createdAt),
			CompletedAt:       intPtrToU64Ptr(completedAt),
		}, nil
	case errors.Is(err, pgx.ErrNoRows):
		return nil, nil
	default:
		return nil, storeErrorf("get intent: %v", err)
	}
}

func (s *PostgresStore) ReapIntents(ctx context.Context, appliedBefore uint64) (uint64, error) {
	tag, err := s.pool.Exec(ctx,
		"DELETE FROM intents WHERE status = 'applied' AND completed_at IS NOT NULL AND completed_at < $1",
		clampI64(appliedBefore))
	if err != nil {
		return 0, storeErrorf("reap intents: %v", err)
	}
	return uint64(tag.RowsAffected()), nil
}

// --- Jobs ---

func (s *PostgresStore) RecordJob(ctx context.Context, job core.JobRecord) error {
	var durationSecs *int64
	if job.DurationSecs != nil {
		v := int64(*job.DurationSecs)
		durationSecs = &v
	}
	_, err := s.pool.Exec(ctx, `
		INSERT INTO jobs (id, cluster, submitter, status, duration_secs, submitted_at)
		VALUES ($1, $2, $3, $4, $5, $6)
		ON CONFLICT (id) DO UPDATE SET status = excluded.status, duration_secs = excluded.duration_secs
	`, job.Id, job.Cluster, job.Submitter, job.Status, durationSecs, int64(job.SubmittedAt))
	if err != nil {
		return storeErrorf("record job: %v", err)
	}
	return nil
}

func (s *PostgresStore) ListJobs(ctx context.Context) ([]core.JobRecord, error) {
	rows, err := s.pool.Query(ctx,
		"SELECT id, cluster, submitter, status, duration_secs, submitted_at FROM jobs ORDER BY submitted_at DESC")
	if err != nil {
		return nil, storeErrorf("list jobs: %v", err)
	}
	defer rows.Close()

	out := make([]core.JobRecord, 0)
	for rows.Next() {
		var (
			id, cluster, submitter, status string
			durationSecs                   *int64
			submittedAt                    int64
		)
		if err := rows.Scan(&id, &cluster, &submitter, &status, &durationSecs, &submittedAt); err != nil {
			return nil, storeErrorf("list jobs: %v", err)
		}
		out = append(out, core.JobRecord{
			Id: id, Cluster: cluster, Submitter: submitter, Status: status,
			DurationSecs: intPtrToU64Ptr(durationSecs), SubmittedAt: uint64(submittedAt),
		})
	}
	if err := rows.Err(); err != nil {
		return nil, storeErrorf("list jobs: %v", err)
	}
	return out, nil
}

// --- Pools ---

// UpsertPool mirrors UpsertDesired's transaction + advisory-lock
// discipline (store_postgres.rs:763-824), keyed by "pool/"+name so it
// never collides with a cluster id's lock key.
func (s *PostgresStore) UpsertPool(ctx context.Context, name string, spec core.PoolSpec) (uint64, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return 0, storeErrorf("begin transaction: %v", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if _, err := tx.Exec(ctx, "SELECT pg_advisory_xact_lock(hashtext($1))", "pool/"+name); err != nil {
		return 0, storeErrorf("advisory lock: %v", err)
	}

	generation, err := func() (uint64, error) {
		var curJSON string
		var curGen int64
		err := tx.QueryRow(ctx, "SELECT spec_json, generation FROM pools WHERE name = $1", name).
			Scan(&curJSON, &curGen)
		switch {
		case err == nil:
			var cur core.PoolSpec
			if uerr := json.Unmarshal([]byte(curJSON), &cur); uerr != nil {
				return 0, jsonErr(uerr)
			}
			if poolSpecChanged(&cur, &spec) {
				return uint64(curGen) + 1, nil
			}
			return uint64(curGen), nil
		case errors.Is(err, pgx.ErrNoRows):
			return 1, nil
		default:
			return 0, storeErrorf("read pool: %v", err)
		}
	}()
	if err != nil {
		return 0, err
	}

	specJSON, err := json.Marshal(spec)
	if err != nil {
		return 0, jsonErr(err)
	}
	_, err = tx.Exec(ctx, `
		INSERT INTO pools (name, spec_json, generation, created_at)
		VALUES ($1, $2, $3, $4)
		ON CONFLICT (name) DO UPDATE SET
			spec_json = excluded.spec_json,
			generation = excluded.generation
	`, name, string(specJSON), int64(generation), int64(NowUnix()))
	if err != nil {
		return 0, storeErrorf("upsert pool: %v", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return 0, storeErrorf("commit: %v", err)
	}
	return generation, nil
}

func (s *PostgresStore) GetPool(ctx context.Context, name string) (*StoredPool, error) {
	row := s.pool.QueryRow(ctx, "SELECT "+poolColumns+" FROM pools WHERE name = $1", name)
	p, err := scanPool(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &p, nil
}

func (s *PostgresStore) ListPools(ctx context.Context) ([]StoredPool, error) {
	rows, err := s.pool.Query(ctx, "SELECT "+poolColumns+" FROM pools")
	if err != nil {
		return nil, storeErrorf("list pools: %v", err)
	}
	defer rows.Close()

	out := make([]StoredPool, 0)
	for rows.Next() {
		p, err := scanPool(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	if err := rows.Err(); err != nil {
		return nil, storeErrorf("list pools: %v", err)
	}
	return out, nil
}

func (s *PostgresStore) DeletePool(ctx context.Context, name string) error {
	tag, err := s.pool.Exec(ctx, "DELETE FROM pools WHERE name = $1", name)
	if err != nil {
		return storeErrorf("delete pool: %v", err)
	}
	if tag.RowsAffected() == 0 {
		return errNoSuchPool(name)
	}
	return nil
}

func (s *PostgresStore) RecordPoolObservation(ctx context.Context, name, observedJSON string) error {
	_, err := s.pool.Exec(ctx,
		"UPDATE pools SET observed_json = $1, observed_at = $2 WHERE name = $3",
		observedJSON, int64(NowUnix()), name)
	if err != nil {
		return storeErrorf("record pool observation: %v", err)
	}
	return nil
}

// --- Allocations ---

func (s *PostgresStore) UpsertAllocation(ctx context.Context, alloc core.AllocationSpec) error {
	specJSON, err := json.Marshal(alloc)
	if err != nil {
		return jsonErr(err)
	}
	_, err = s.pool.Exec(ctx, `
		INSERT INTO allocations (pool, project, spec_json)
		VALUES ($1, $2, $3)
		ON CONFLICT (pool, project) DO UPDATE SET spec_json = excluded.spec_json
	`, alloc.Pool, alloc.Project, string(specJSON))
	if err != nil {
		return storeErrorf("upsert allocation: %v", err)
	}
	return nil
}

func (s *PostgresStore) ListAllocations(ctx context.Context, pool string) ([]core.AllocationSpec, error) {
	rows, err := s.pool.Query(ctx, "SELECT spec_json FROM allocations WHERE pool = $1", pool)
	if err != nil {
		return nil, storeErrorf("list allocations: %v", err)
	}
	defer rows.Close()

	out := make([]core.AllocationSpec, 0)
	for rows.Next() {
		var specJSON string
		if err := rows.Scan(&specJSON); err != nil {
			return nil, storeErrorf("list allocations: %v", err)
		}
		var a core.AllocationSpec
		if err := json.Unmarshal([]byte(specJSON), &a); err != nil {
			return nil, jsonErr(err)
		}
		out = append(out, a)
	}
	if err := rows.Err(); err != nil {
		return nil, storeErrorf("list allocations: %v", err)
	}
	return out, nil
}

func (s *PostgresStore) DeleteAllocation(ctx context.Context, pool, project string) error {
	tag, err := s.pool.Exec(ctx, "DELETE FROM allocations WHERE pool = $1 AND project = $2", pool, project)
	if err != nil {
		return storeErrorf("delete allocation: %v", err)
	}
	if tag.RowsAffected() == 0 {
		return errNoSuchAllocation(pool, project)
	}
	return nil
}

// --- Usage samples ---

// RecordUsageSamples mirrors store_postgres.rs:912-943: one transaction
// per batch so a tick's samples land atomically.
func (s *PostgresStore) RecordUsageSamples(ctx context.Context, samples []UsageSample) error {
	if len(samples) == 0 {
		return nil
	}
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return storeErrorf("begin transaction: %v", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	for _, smp := range samples {
		if _, err := tx.Exec(ctx,
			"INSERT INTO usage_samples (ts, project, pool, resource, quantity, source) VALUES ($1, $2, $3, $4, $5, $6)",
			clampI64(smp.Ts), smp.Project, smp.Pool, smp.Resource, smp.Quantity, smp.Source.AsStr()); err != nil {
			return storeErrorf("insert usage sample: %v", err)
		}
	}
	if err := tx.Commit(ctx); err != nil {
		return storeErrorf("commit: %v", err)
	}
	return nil
}

func (s *PostgresStore) UsageSamples(ctx context.Context, project, pool *string, from, to uint64) ([]UsageSample, error) {
	// $3/$4 need an explicit ::text cast: unlike sqlx (which conveys the
	// bind type up front), pgx's default extended-protocol Parse leaves
	// parameter type inference to Postgres, and a placeholder used only in
	// an `IS NULL` context gives the planner nothing to infer from
	// (SQLSTATE 42P18) — the cast also lets each value bind once instead
	// of the Rust reference's $3/$4, $5/$6 double-bind.
	rows, err := s.pool.Query(ctx, `
		SELECT ts, project, pool, resource, quantity, source FROM usage_samples
		WHERE ts >= $1 AND ts <= $2
		AND ($3::text IS NULL OR project = $3)
		AND ($4::text IS NULL OR pool = $4)
		ORDER BY ts ASC
	`, clampI64(from), clampI64(to), project, pool)
	if err != nil {
		return nil, storeErrorf("usage samples: %v", err)
	}
	defer rows.Close()

	out := make([]UsageSample, 0)
	for rows.Next() {
		var (
			ts                            int64
			projectVal, poolVal, resource string
			quantity                      float64
			sourceStr                     string
		)
		if err := rows.Scan(&ts, &projectVal, &poolVal, &resource, &quantity, &sourceStr); err != nil {
			return nil, storeErrorf("usage samples: %v", err)
		}
		source, err := ParseUsageSource(sourceStr)
		if err != nil {
			return nil, err
		}
		out = append(out, UsageSample{
			Ts: uint64(ts), Project: projectVal, Pool: poolVal, Resource: resource,
			Quantity: quantity, Source: source,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, storeErrorf("usage samples: %v", err)
	}
	return out, nil
}

// --- Governance policy ---

func (s *PostgresStore) GetPolicy(ctx context.Context) (*StoredPolicy, error) {
	var v string
	err := s.pool.QueryRow(ctx, "SELECT value FROM control WHERE key = 'policy'").Scan(&v)
	switch {
	case err == nil:
		var p StoredPolicy
		if uerr := json.Unmarshal([]byte(v), &p); uerr != nil {
			return nil, jsonErr(uerr)
		}
		return &p, nil
	case errors.Is(err, pgx.ErrNoRows):
		return nil, nil
	default:
		return nil, storeErrorf("get policy: %v", err)
	}
}

func (s *PostgresStore) SetPolicy(ctx context.Context, policy *StoredPolicy) error {
	b, err := json.Marshal(policy)
	if err != nil {
		return jsonErr(err)
	}
	_, err = s.pool.Exec(ctx,
		"INSERT INTO control (key, value) VALUES ('policy', $1) ON CONFLICT (key) DO UPDATE SET value = excluded.value",
		string(b))
	if err != nil {
		return storeErrorf("set policy: %v", err)
	}
	return nil
}

func (s *PostgresStore) SeedPolicy(ctx context.Context, policy *StoredPolicy) (bool, error) {
	b, err := json.Marshal(policy)
	if err != nil {
		return false, jsonErr(err)
	}
	tag, err := s.pool.Exec(ctx,
		"INSERT INTO control (key, value) VALUES ('policy', $1) ON CONFLICT (key) DO NOTHING",
		string(b))
	if err != nil {
		return false, storeErrorf("seed policy: %v", err)
	}
	return tag.RowsAffected() > 0, nil
}

// --- Audit ---

// RecordAudit mirrors store_postgres.rs:982-1028: pg_advisory_xact_lock on
// a fixed 'audit_chain' key serializes the read-newest-hash/compute/insert
// sequence across every connection and process, so a new row's chain hash
// always chains from the true newest row — the multi-replica-correct
// analog of SqliteStore.auditMu (a single-process in-memory mutex cannot
// serialize across replicas; the ledgered
// postgres_concurrent_audit_appends_keep_one_chain test in
// store_postgres_test.go is exactly the tripwire for a regression here).
func (s *PostgresStore) RecordAudit(ctx context.Context, event *core.AuditEvent) (uint64, error) {
	var requiredJSON *string
	if event.Required != nil {
		b, err := json.Marshal(*event.Required)
		if err != nil {
			return 0, jsonErr(err)
		}
		str := string(b)
		requiredJSON = &str
	}
	grantedRoles := event.GrantedRoles
	if grantedRoles == nil {
		grantedRoles = []string{}
	}
	grantedRolesJSON, err := json.Marshal(grantedRoles)
	if err != nil {
		return 0, jsonErr(err)
	}

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return 0, storeErrorf("begin transaction: %v", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if _, err := tx.Exec(ctx, "SELECT pg_advisory_xact_lock(hashtext('audit_chain'))"); err != nil {
		return 0, storeErrorf("advisory lock: %v", err)
	}

	var prev string
	err = tx.QueryRow(ctx, "SELECT chain_hash FROM audit_events ORDER BY seq DESC LIMIT 1").Scan(&prev)
	switch {
	case err == nil:
		// prev already set.
	case errors.Is(err, pgx.ErrNoRows):
		prev = AuditGenesisHash
	default:
		return 0, storeErrorf("read chain head: %v", err)
	}
	chainHash := AuditChainHash(prev, event)

	var seq int64
	err = tx.QueryRow(ctx, `
		INSERT INTO audit_events
		(ts, subject, decision, reason, action, cluster, method, path,
		 status, latency_ms, required_json, granted_roles, chain_hash)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
		RETURNING seq
	`, clampI64(event.Ts), event.Subject, event.Decision.AsStr(), event.Reason, event.Action,
		event.Cluster, event.Method, event.Path, event.Status, event.LatencyMs,
		requiredJSON, string(grantedRolesJSON), chainHash).Scan(&seq)
	if err != nil {
		return 0, storeErrorf("record audit: %v", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return 0, storeErrorf("commit: %v", err)
	}
	return uint64(seq), nil
}

func (s *PostgresStore) ListAudit(ctx context.Context, filter core.AuditFilter) ([]AuditRow, *uint64, error) {
	var b strings.Builder
	b.WriteString("SELECT " + auditColumns + " FROM audit_events WHERE 1=1")
	args := make([]any, 0, 8)
	// arg appends v and returns its placeholder — Postgres's numbered
	// placeholders let each filter field bind exactly once, unlike
	// SQLite's `?` requiring the value repeated per `?`.
	arg := func(v any) string {
		args = append(args, v)
		return fmt.Sprintf("$%d", len(args))
	}

	if filter.Cursor != nil {
		b.WriteString(" AND seq < " + arg(clampI64(*filter.Cursor)))
	}
	if filter.From != nil {
		b.WriteString(" AND ts >= " + arg(clampI64(*filter.From)))
	}
	if filter.To != nil {
		b.WriteString(" AND ts <= " + arg(clampI64(*filter.To)))
	}
	if filter.Subject != nil {
		b.WriteString(" AND subject = " + arg(*filter.Subject))
	}
	if filter.Cluster != nil {
		b.WriteString(" AND cluster = " + arg(*filter.Cluster))
	}
	if filter.Method != nil {
		b.WriteString(" AND method = " + arg(*filter.Method))
	}
	if filter.PathPrefix != nil {
		// substr(path, 1, length($n)) = $n instead of LIKE, so a prefix
		// containing % or _ can't go wildcard.
		p := arg(*filter.PathPrefix)
		fmt.Fprintf(&b, " AND substr(path, 1, length(%s)) = %s", p, p)
	}
	if filter.MinStatus != nil {
		// NULL status rows are excluded: NULL >= n is never true in SQL.
		b.WriteString(" AND status >= " + arg(int64(*filter.MinStatus)))
	}
	if filter.Decision != nil {
		b.WriteString(" AND decision = " + arg(filter.Decision.AsStr()))
	}
	if filter.Reason != nil {
		b.WriteString(" AND reason = " + arg(*filter.Reason))
	}
	// One row beyond the page tells us whether a next page exists.
	limit := filter.EffectiveLimit()
	b.WriteString(" ORDER BY seq DESC LIMIT " + arg(int64(limit)+1))

	rows, err := s.pool.Query(ctx, b.String(), args...)
	if err != nil {
		return nil, nil, storeErrorf("list audit: %v", err)
	}
	defer rows.Close()

	out := make([]AuditRow, 0)
	for rows.Next() {
		seq, event, _, err := scanAuditRow(rows, false)
		if err != nil {
			return nil, nil, err
		}
		out = append(out, AuditRow{Seq: seq, Event: event})
	}
	if err := rows.Err(); err != nil {
		return nil, nil, storeErrorf("list audit: %v", err)
	}

	var nextCursor *uint64
	if uint32(len(out)) > limit {
		out = out[:limit]
		seq := out[len(out)-1].Seq
		nextCursor = &seq
	}
	return out, nextCursor, nil
}

// AuditChain mirrors store_postgres.rs:1100-1139.
func (s *PostgresStore) AuditChain(ctx context.Context, fromSeq *uint64, limit uint32) (AuditChainWindow, error) {
	head := AuditGenesisHash
	if fromSeq != nil && *fromSeq > 1 {
		var h string
		err := s.pool.QueryRow(ctx,
			"SELECT chain_hash FROM audit_events WHERE seq < $1 ORDER BY seq DESC LIMIT 1",
			clampI64(*fromSeq)).Scan(&h)
		switch {
		case err == nil:
			head = h
		case errors.Is(err, pgx.ErrNoRows):
			// No preceding row: keep genesis.
		default:
			return AuditChainWindow{}, storeErrorf("read chain head: %v", err)
		}
	}

	var b strings.Builder
	b.WriteString("SELECT " + auditColumns + ", chain_hash FROM audit_events")
	args := make([]any, 0, 2)
	if fromSeq != nil {
		args = append(args, clampI64(*fromSeq))
		fmt.Fprintf(&b, " WHERE seq >= $%d", len(args))
	}
	args = append(args, int64(limit))
	fmt.Fprintf(&b, " ORDER BY seq ASC LIMIT $%d", len(args))

	rows, err := s.pool.Query(ctx, b.String(), args...)
	if err != nil {
		return AuditChainWindow{}, storeErrorf("audit chain: %v", err)
	}
	defer rows.Close()

	out := make([]ChainedAuditRow, 0)
	for rows.Next() {
		seq, event, chainHash, err := scanAuditRow(rows, true)
		if err != nil {
			return AuditChainWindow{}, err
		}
		out = append(out, ChainedAuditRow{Seq: seq, Event: event, ChainHash: chainHash})
	}
	if err := rows.Err(); err != nil {
		return AuditChainWindow{}, storeErrorf("audit chain: %v", err)
	}
	return AuditChainWindow{Head: head, Rows: out}, nil
}

// --- Local auth: users ---

// pgScanLocalUser is scanCluster's Postgres-side counterpart for
// local_users: identical column order to localUserColumns, but disabled is
// a real BOOLEAN here (SqliteStore's local_users.disabled is INTEGER 0/1,
// scanned as int64 — see scanLocalUser in store_sqlite.go).
func pgScanLocalUser(row rowScanner) (core.LocalUserRecord, error) {
	var (
		username     string
		email        *string
		passwordHash string
		roleStr      string
		disabled     bool
		createdAt    int64
		failedLogins int64
		lockedUntil  *int64
	)
	if err := row.Scan(&username, &email, &passwordHash, &roleStr, &disabled,
		&createdAt, &failedLogins, &lockedUntil); err != nil {
		return core.LocalUserRecord{}, err
	}
	role, ok := core.ParseLocalRole(roleStr)
	if !ok {
		return core.LocalUserRecord{}, errBadLocalRole(roleStr)
	}
	return core.LocalUserRecord{
		Username:     username,
		Email:        email,
		PasswordHash: passwordHash,
		Role:         role,
		Disabled:     disabled,
		CreatedAt:    uint64(createdAt),
		FailedLogins: uint32(failedLogins),
		LockedUntil:  intPtrToU64Ptr(lockedUntil),
	}, nil
}

func (s *PostgresStore) CreateLocalUser(ctx context.Context, username string, email *string, passwordHash string, role core.LocalRole) error {
	_, err := s.pool.Exec(ctx, `
		INSERT INTO local_users (username, email, password_hash, role, created_at)
		VALUES ($1, $2, $3, $4, $5)
	`, username, email, passwordHash, role.AsStr(), int64(NowUnix()))
	switch {
	case err == nil:
		return nil
	case isPgUniqueViolation(err):
		return errLocalUserAlreadyExists(username)
	default:
		return storeErrorf("create local user: %v", err)
	}
}

func (s *PostgresStore) GetLocalUser(ctx context.Context, username string) (*core.LocalUserRecord, error) {
	row := s.pool.QueryRow(ctx, "SELECT "+localUserColumns+" FROM local_users WHERE username = $1", username)
	u, err := pgScanLocalUser(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}

func (s *PostgresStore) ListLocalUsers(ctx context.Context) ([]core.LocalUserRecord, error) {
	rows, err := s.pool.Query(ctx, "SELECT "+localUserColumns+" FROM local_users ORDER BY username ASC")
	if err != nil {
		return nil, storeErrorf("list local users: %v", err)
	}
	defer rows.Close()

	out := make([]core.LocalUserRecord, 0)
	for rows.Next() {
		u, err := pgScanLocalUser(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, u)
	}
	if err := rows.Err(); err != nil {
		return nil, storeErrorf("list local users: %v", err)
	}
	return out, nil
}

func (s *PostgresStore) SetLocalUserPassword(ctx context.Context, username, passwordHash string) error {
	tag, err := s.pool.Exec(ctx, "UPDATE local_users SET password_hash = $1 WHERE username = $2", passwordHash, username)
	if err != nil {
		return storeErrorf("set local user password: %v", err)
	}
	if tag.RowsAffected() == 0 {
		return errNoSuchLocalUser(username)
	}
	return nil
}

func (s *PostgresStore) SetLocalUserRole(ctx context.Context, username string, role core.LocalRole) error {
	tag, err := s.pool.Exec(ctx, "UPDATE local_users SET role = $1 WHERE username = $2", role.AsStr(), username)
	if err != nil {
		return storeErrorf("set local user role: %v", err)
	}
	if tag.RowsAffected() == 0 {
		return errNoSuchLocalUser(username)
	}
	return nil
}

func (s *PostgresStore) SetLocalUserDisabled(ctx context.Context, username string, disabled bool) error {
	tag, err := s.pool.Exec(ctx, "UPDATE local_users SET disabled = $1 WHERE username = $2", disabled, username)
	if err != nil {
		return storeErrorf("set local user disabled: %v", err)
	}
	if tag.RowsAffected() == 0 {
		return errNoSuchLocalUser(username)
	}
	return nil
}

func (s *PostgresStore) SetLoginLockout(ctx context.Context, username string, failedLogins uint32, lockedUntil *uint64) error {
	var lockedUntilArg *int64
	if lockedUntil != nil {
		v := clampI64(*lockedUntil)
		lockedUntilArg = &v
	}
	tag, err := s.pool.Exec(ctx,
		"UPDATE local_users SET failed_logins = $1, locked_until = $2 WHERE username = $3",
		int64(failedLogins), lockedUntilArg, username)
	if err != nil {
		return storeErrorf("set login lockout: %v", err)
	}
	if tag.RowsAffected() == 0 {
		return errNoSuchLocalUser(username)
	}
	return nil
}

// RecordLoginFailure/RecordLoginSuccess implement the shared lockout state
// machine (NextLoginFailureState) against this store's own
// GetLocalUser/SetLoginLockout — same body as SqliteStore's/MemoryStore's
// (the Go equivalent of the Rust trait's default method, which Go
// interfaces cannot express).
func (s *PostgresStore) RecordLoginFailure(ctx context.Context, username string) error {
	user, err := s.GetLocalUser(ctx, username)
	if err != nil {
		return err
	}
	if user == nil {
		return errNoSuchLocalUser(username)
	}
	failed, locked := NextLoginFailureState(user.FailedLogins, NowUnix())
	return s.SetLoginLockout(ctx, username, failed, locked)
}

func (s *PostgresStore) RecordLoginSuccess(ctx context.Context, username string) error {
	return s.SetLoginLockout(ctx, username, 0, nil)
}

// --- Local auth: API tokens ---

// pgScanApiToken is scanApiToken's Postgres-side counterpart: identical
// column order to apiTokenColumns, but revoked is a real BOOLEAN here.
func pgScanApiToken(row rowScanner) (core.ApiTokenRecord, error) {
	var (
		prefix, tokenHash, username, label string
		createdAt, expiresAt               int64
		revoked                            bool
		lastUsedAt                         *int64
	)
	if err := row.Scan(&prefix, &tokenHash, &username, &label, &createdAt, &expiresAt, &revoked, &lastUsedAt); err != nil {
		return core.ApiTokenRecord{}, err
	}
	return core.ApiTokenRecord{
		Prefix:     prefix,
		TokenHash:  tokenHash,
		Username:   username,
		Label:      label,
		CreatedAt:  uint64(createdAt),
		ExpiresAt:  uint64(expiresAt),
		Revoked:    revoked,
		LastUsedAt: intPtrToU64Ptr(lastUsedAt),
	}, nil
}

func (s *PostgresStore) CreateApiToken(ctx context.Context, record core.ApiTokenRecord) error {
	_, err := s.pool.Exec(ctx, `
		INSERT INTO api_tokens (prefix, token_hash, username, label, created_at, expires_at, revoked, last_used_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
	`, record.Prefix, record.TokenHash, record.Username, record.Label,
		clampI64(record.CreatedAt), clampI64(record.ExpiresAt), record.Revoked, record.LastUsedAt)
	switch {
	case err == nil:
		return nil
	case isPgUniqueViolation(err):
		return errApiTokenAlreadyExists(record.Prefix)
	default:
		return storeErrorf("create api token: %v", err)
	}
}

func (s *PostgresStore) GetApiTokenByPrefix(ctx context.Context, prefix string) (*core.ApiTokenRecord, error) {
	row := s.pool.QueryRow(ctx, "SELECT "+apiTokenColumns+" FROM api_tokens WHERE prefix = $1", prefix)
	t, err := pgScanApiToken(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, storeErrorf("get api token: %v", err)
	}
	return &t, nil
}

func (s *PostgresStore) ListApiTokens(ctx context.Context, username string) ([]core.ApiTokenRecord, error) {
	rows, err := s.pool.Query(ctx,
		"SELECT "+apiTokenColumns+" FROM api_tokens WHERE username = $1 ORDER BY created_at DESC", username)
	if err != nil {
		return nil, storeErrorf("list api tokens: %v", err)
	}
	defer rows.Close()

	out := make([]core.ApiTokenRecord, 0)
	for rows.Next() {
		t, err := pgScanApiToken(rows)
		if err != nil {
			return nil, storeErrorf("list api tokens: %v", err)
		}
		out = append(out, t)
	}
	if err := rows.Err(); err != nil {
		return nil, storeErrorf("list api tokens: %v", err)
	}
	return out, nil
}

// RevokeApiToken is owner-scoped: the UPDATE matches only rows the caller
// owns, so revoking someone else's token and revoking a nonexistent one
// are indistinguishable ("no such token") — no ownership probing.
func (s *PostgresStore) RevokeApiToken(ctx context.Context, prefix, username string) error {
	tag, err := s.pool.Exec(ctx,
		"UPDATE api_tokens SET revoked = TRUE WHERE prefix = $1 AND username = $2", prefix, username)
	if err != nil {
		return storeErrorf("revoke api token: %v", err)
	}
	if tag.RowsAffected() == 0 {
		return errNoSuchApiToken(prefix)
	}
	return nil
}

func (s *PostgresStore) TouchApiToken(ctx context.Context, prefix string, now uint64) error {
	_, err := s.pool.Exec(ctx, "UPDATE api_tokens SET last_used_at = $1 WHERE prefix = $2", clampI64(now), prefix)
	if err != nil {
		return storeErrorf("touch api token: %v", err)
	}
	return nil
}

// --- Scoped role assignments ---

// UpsertRoleAssignment re-upsert preserves the original created_at (DO
// NOTHING on the triple's PK), matching MemoryStore/SqliteStore.
func (s *PostgresStore) UpsertRoleAssignment(ctx context.Context, principal, role, scope string) error {
	_, err := s.pool.Exec(ctx, `
		INSERT INTO role_assignments (principal, role, scope, created_at)
		VALUES ($1, $2, $3, $4)
		ON CONFLICT (principal, role, scope) DO NOTHING
	`, principal, role, scope, int64(NowUnix()))
	if err != nil {
		return storeErrorf("upsert role assignment: %v", err)
	}
	return nil
}

func (s *PostgresStore) ListRoleAssignments(ctx context.Context, principal *string) ([]RoleAssignment, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT principal, role, scope, created_at FROM role_assignments
		WHERE ($1::text IS NULL OR principal = $1)
		ORDER BY principal ASC, scope ASC, role ASC
	`, principal)
	if err != nil {
		return nil, storeErrorf("list role assignments: %v", err)
	}
	defer rows.Close()

	out := make([]RoleAssignment, 0)
	for rows.Next() {
		var a RoleAssignment
		var createdAt int64
		if err := rows.Scan(&a.Principal, &a.Role, &a.Scope, &createdAt); err != nil {
			return nil, storeErrorf("list role assignments: %v", err)
		}
		a.CreatedAt = uint64(createdAt)
		out = append(out, a)
	}
	if err := rows.Err(); err != nil {
		return nil, storeErrorf("list role assignments: %v", err)
	}
	return out, nil
}

func (s *PostgresStore) DeleteRoleAssignment(ctx context.Context, principal, role, scope string) error {
	tag, err := s.pool.Exec(ctx,
		"DELETE FROM role_assignments WHERE principal = $1 AND role = $2 AND scope = $3", principal, role, scope)
	if err != nil {
		return storeErrorf("delete role assignment: %v", err)
	}
	if tag.RowsAffected() == 0 {
		return errNoSuchAssignment(principal, role, scope)
	}
	return nil
}
